### PR TITLE
Add GitLab social sponsorship logo

### PR DESCRIPTION
**Pull request by juliusv**
I had to introduce a new logo width class because the stacked GitLab
logo otherwise looked overly huge in comparison to the others.

### CODE REVIEW

**Comment by juliusv** [comment]
@RichiH

**Comment by RichiH** [comment]
LGTM.

@tomwilkie do you know when we can put Grafana there? :)

**Comment by tomwilkie** [comment]
Yeah, lets go for it!  I'll make a PR now.

**Comment by RichiH** [comment]
Thanks for the contract, I will forward on the org list as well. Looking forward to your PR :)

**Pull request merged**
