### PR TITLE
Add COVID-19 notice

### PR DESCRIPTION
**Pull request by juliusv**
With verbiage as provided by the CNCF / LF.

Signed-off-by: Julius Volz <julius.volz@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
@RichiH

**Comment by roidelapluie** [comment]
No netlify preview?

**Comment by juliusv** [comment]
Here's the deploy preview, not sure why Netlify didn't add it here: https://5e7099c58afa160009ea3f9f--promcon.netlify.com/2020-vancouver/covid-19/

**Comment by roidelapluie** [comment]
lgtm

**Pull request merged**
