### PR TITLE
Improved Docs

### PR DESCRIPTION
**Pull request by jaimatadiletsrock**

### CODE REVIEW

**Comment by juliusv** [comment]
Sorry, without further info, will just close this - looks like possibly spam / an accident?

**Comment by probonopd** [comment]
Unlikely that this is an accident - check these out:

https://github.com/zencashio/website/pull/35
https://github.com/keep-network/website/pull/268
https://github.com/grails/grails-static-website/pull/113
https://github.com/neon-bindings/website/pull/153
https://github.com/smoke-trees/website/pull/31
https://github.com/rubykube/website/pull/84
https://github.com/jacobtomlinson/website/pull/108
https://github.com/maunium/dontasktoask.com/pull/24
https://github.com/promcon/website/pull/158
https://github.com/NYC-Camp/website/pull/293

cc @stapelberg

**Comment by juliusv** [comment]
Yep, just saw his tweet, thanks :)

**Comment by probonopd** [comment]
Only question, what is this supposed to accomplish?

**Comment by juliusv** [comment]
@probonopd Maybe probing repos for auto-merge to later smuggle in vulnerabilities.

**Comment by juliusv** [comment]
Ah, seems to be Hacktoberfest: https://twitter.com/MarijnJH/status/1311431744680321024?s=19

**Comment by iHiD** [comment]
Tag with the `invalid` label (which means hackerfest know to ignore them), report/block them on GitHub and GitHub will delete their account. We're on our 5th person already tonight over on Exercism - its ridiculous! 🙂

**Comment by juliusv** [comment]
@iHiD I simply turned on interaction limits for this repo for now. Ain't got time to tag & report everything separately without getting paid for it ;)

**Pull request closed without merging**
