### PR TITLE
Link to diversity scholarship form

### PR DESCRIPTION
**Pull request by grobie**
@juliusv @RichiH

### CODE REVIEW

**Comment by juliusv** [comment]
:+1:

**Comment by RichiH** [comment]
Lgtm

Sent by mobile; please excuse my brevity.

**Comment by juliusv** [comment]
@grobie Wanna make this a full website section again like last year? See 88894bf0fe0ec303dc66658dfa36e6984346a376

**Comment by grobie** [comment]
Done https://github.com/promcon/website/commit/f2fb1d3e950c1133a9fa94bf6f8ede4c531e3934

**Pull request merged**
