### PR TITLE
Remove proposals page, publish schedule.

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by juliusv** [comment]
@brian-brazil @fabxc @beorn7 

You can look at the (unpublished) schedule at https://promcon.io/schedule/

It includes links to talk abstracts and speaker bios.

I would like to publish this soon (before end of month). Looks ok?

**Comment by juliusv** [comment]
Once it's published, I will mail all speakers, saying that it's now ok to post on social media about their accepted talks, and I will also ask them to verify that their bios and abstracts look ok.

**Comment by brian-brazil** [comment]
:+1:

**Comment by fabxc** [comment]
:+1:

**Comment by fabxc** [comment]
:+1:

**Comment by beorn7** [comment]
Christian Svensson's bio link yields a 404

Otherwise :+1:

**Comment by juliusv** [comment]
Oh thanks. Somehow I deleted him accidentally in an earlier commit. Readded.

**Pull request merged**
